# to build 3hdeng/syntax-api:dragnn
FROM 3hdeng/dragnn:2.7

ENV PYTHONIOENCODING UTF-8

RUN  pip install -U Flask &&  echo "Flask installed"
RUN  pip install flask-swaggerui &&  echo "flask-swaggerui installed"

COPY syntaxnet_wrapper /opt/syntaxnet_wrapper
RUN cd /opt/syntaxnet_wrapper && python setup.py install

RUN pip install -U flask-cors

CMD []


#=====Dockerfile_dragnn
#dragnn, PythonPaths, bazel-bin
#need to perform bazel build :tutorial_1
#$ /opt/tensorflow/syntaxnet/examples/dragnn# bazel build :tutorial_1
