FROM 3hdeng/syntax-wrapper:2.7
#to build 3hdeng/syntax-api:2.7
RUN apt-get update \
    && pip install --upgrade pip

RUN  pip install -U Flask &&  echo "Flask installed"
#RUN  pip install -U flask-swagger &&  echo "flask-swagger installed"
#RUN  pip install flask-swagger-ui &&  echo "flask-swagger-ui installed"
RUN  pip install flask-swaggerui &&  echo "flask-swaggerui installed"

#COPY /home/elf/workspaces/syntaxnet_wrapper /opt/syntaxnet_wrapper
ENV PYTHONIOENCODING UTF-8
CMD []
