FROM python:2.7
#to build 3hdeng/syntax-api:2.7
RUN apt-get update \
    && pip install --upgrade pip

RUN  pip install -U Flask &&  echo "Flask installed"
#RUN  pip install -U flask-swagger &&  echo "flask-swagger installed"
#RUN  pip install flask-swagger-ui &&  echo "flask-swagger-ui installed"
RUN  pip install flask-swaggerui &&  echo "flask-swaggerui installed"

#=== install syntaxnet-wrapper
# COPY syntaxnet-wrapper /opt/syntaxnet-wrapper
# RUN cd /opt/syntaxnet-wrapper && python setup.py install

#RUN apt-get install -y  software-properties-common 
#RUN add-apt-repository -y ppa:openjdk-r/ppa
#RUN apt-get update -&& apt-get install -y openjdk-8-jdk
RUN echo "deb http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list.d/jessie.list && apt-get update && \
  apt install -yt jessie-backports  openjdk-8-jre-headless ca-certificates-java && \
  apt install -y  openjdk-8-jre  openjdk-8-jdk-headless  openjdk-8-jdk  && \
   update-alternatives --config java

RUN rm /etc/apt/sources.list.d/jessie.list && \
   apt-get clean && \
   rm -rf /var/lib/apt/lists/*

RUN  apt-get update && apt-get install -y swig unzip wget python-mock


RUN  pip install -U protobuf==3.0.0b2 \
    && pip install asciitree \
    && pip install numpy \
    && wget https://github.com/bazelbuild/bazel/releases/download/0.4.3/bazel-0.4.3-installer-linux-x86_64.sh \
    && chmod +x bazel-0.4.3-installer-linux-x86_64.sh \
    && ./bazel-0.4.3-installer-linux-x86_64.sh \
    && apt-get autoremove

#COPY /home/elf/workspaces/syntaxnet_wrapper /opt/syntaxnet_wrapper
CMD []
