target:	
	cd /opt/tensorflow/syntaxnet && \
	cp syntaxnet/models/parsey_universal/parse.sh syntaxnet/parse.sh && \
	cp syntaxnet/models/parsey_universal/tokenize.sh syntaxnet/tokenize.sh && \
	cp syntaxnet/models/parsey_universal/tokenize_zh.sh syntaxnet/tokenize_zh.sh

